services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: sluser
      POSTGRES_PASSWORD: slpass
      POSTGRES_DB: slgame
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sluser -d slgame -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build: ./server
    environment:
      DATABASE_URL: postgres://sluser:slpass@db:5432/slgame
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
