version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: sluser
      POSTGRES_PASSWORD: slpass
      POSTGRES_DB: slgame
    ports:
      - "5432:5432"
  api:
    build: ./server
    environment:
      DATABASE_URL: postgres://sluser:slpass@db:5432/slgame
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
